EXEC   = 2LPTic

OBJS   = main.o power.o allvars.o save.o read_param.o  read_glass.o  \
         nrsrc/nrutil.o nrsrc/qromb.o nrsrc/polint.o nrsrc/trapzd.o

INCL   = allvars.h proto.h  nrsrc/nrutil.h  Makefile



#OPT   +=  -DPRODUCEGAS   # Set this to automatically produce gas particles 
                         # for a single DM species in the input file by interleaved by a half a grid spacing


OPT   +=  -DMULTICOMPONENTGLASSFILE  # set this if the initial glass file contains multiple components

#OPT   +=  -DDIFFERENT_TRANSFER_FUNC  # set this if you want to implement a transfer function that depends on
                                     # particle type

OPT   +=  -DNO64BITID    # switch this on if you want normal 32-bit IDs
#OPT   +=  -DCORRECT_CIC  # only switch this on if particles start from a glass (as opposed to grid)

#OPT += -DONLY_ZA # swith this on if you want ZA initial conditions (2LPT otherwise)

#OPT   += -DOUTPUT_DF     # turn this on to output the linear density field
                         # generated by the code



OPTIONS =  $(OPT)


FFTW_INCL = -I/opt/homebrew/opt/fftw/include
FFTW_LIBS = -L/opt/homebrew/opt/fftw/lib

GSL_LIBS = -L/opt/homebrew/opt/gsl/lib
GSL_INCL = -I/opt/homebrew/opt/gsl/include


CC       =  gcc #/user/bin/gcc 
#MPICHLIB = -L/usr/mpi/gcc/openmpi-1.2.2-1/lib64 -lmpi
MPICHLIB = -L/opt/homebrew/Cellar/open-mpi/5.0.9/lib -lmpi 
MPI_INCL = -I/opt/homebrew/Cellar/open-mpi/5.0.9/include

OPTIMIZE =   -O3 -g    # optimization and warning flags (default)



#ifeq ($(SYSTYPE),"Paco")
#CC       =  gcc     # sets the C-compiler
#OPT      +=  
#OPTIMIZE =   -O3 -g
#GSL_INCL = -I/Users/fvillaescusa/Software/gsl-2.4_lib/include
#GSL_LIBS = -L/Users/fvillaescusa/Software/gsl-2.4_lib/lib
#FFTW_INCL= -I/Users/fvillaescusa/Software/fftw-2.1.5_lib/include
#FFTW_LIBS= -L/Users/fvillaescusa/Software/fftw-2.1.5_lib/lib
#MPICHLIB = -L/Users/fvillaescusa/Software/openmpi-3.0.0_lib/lib -lmpi
#MPI_INCL = -I/Users/fvillaescusa/Software/openmpi-3.0.0_lib/include
#endif



FFTW_LIB =  $(FFTW_LIBS) -lfftw3_mpi -lfftw3

LIBS   =   -lm  $(MPICHLIB)  $(FFTW_LIB)  $(GSL_LIBS)  -lgsl -lgslcblas

CFLAGS =   $(OPTIONS)  $(OPTIMIZE)  $(FFTW_INCL) $(GSL_INCL) $(MPI_INCL)

$(EXEC): $(OBJS) 
	$(CC) $(OPTIMIZE) $(OBJS) $(LIBS) $(MPICHLIB)  -o  $(EXEC)  

$(OBJS): $(INCL) 


.PHONY : clean
clean:
	rm -f $(OBJS) $(EXEC)



